import { arm_left, arm_right, body_up, head_left, head_right, leg_left, leg_right } from "./assets";

export const initialPuzzles = [
    {
        id: 1,
        sizeX: 3,
        sizeY: 4,
        correctX: [3],
        correctY: [1],
        src: head_left,
        startPuz: {
            rotation: -15,
            left: 54,
            bottom: 76,
        },
        puzzWidth: 39,
        puzzHeight: 80,
        puzzRealWidth: 54,
        puzzRealHeight: 90,
        xPosition: '100%',
    },
    {
        id: 2,
        sizeX: 3,
        sizeY: 4,
        correctX: [6],
        correctY: [1],
        src: head_right,
        startPuz: {
            rotation: 0,
            right: 30,
            top: 241,
        },
        puzzWidth: 39,
        puzzHeight: 80,
        puzzRealWidth: 44,
        puzzRealHeight: 90,
    },
    {
        id: 3,
        sizeX: 5,
        sizeY: 8,
        correctX: [1],
        correctY: [6],
        src: arm_left,
        startPuz: {
            rotation: 16,
            top: 51,
            left: 22,
        },
        puzzWidth: 81,
        puzzHeight: 117,
        puzzRealWidth: 90,
        puzzRealHeight: 144,
        yPosition: '100%'
    },
    {
        id: 4,
        sizeX: 7,
        sizeY: 4,
        correctX: [4],
        correctY: [6],
        src: body_up,
        startPuz: {
            rotation: -29,
            right: 34,
            bottom: 61,
        },
        puzzWidth: 111,
        puzzHeight: 65,
        puzzRealWidth: 123,
        puzzRealHeight: 72,
    },
    {
        id: 5,
        sizeX: 5,
        sizeY: 4,
        correctX: [6],
        correctY: [10],
        src: arm_right,
        startPuz: {
            rotation: 25,
            right: 35,
            top: 113,
        },
        puzzWidth: 81,
        puzzHeight: 64,
        puzzRealWidth: 90,
        puzzRealHeight: 72,
    },
    {
        id: 6,
        sizeX: 2,
        sizeY: 3,
        correctX: [4, 6],
        correctY: [14],
        src: leg_left,
        startPuz: {
            rotation: -33,
            right: 142,
            top: 41,
        },
        puzzWidth: 28,
        puzzHeight: 48,
        puzzRealWidth: 36,
        puzzRealHeight: 54,
    },
    {
        id: 7,
        sizeX: 2,
        sizeY: 3,
        correctX: [4, 6],
        correctY: [14],
        src: leg_right,
        startPuz: {
            rotation: 0,
            left: 47,
            top: 222,
        },
        puzzWidth: 28,
        puzzHeight: 48,
        puzzRealWidth: 36,
        puzzRealHeight: 54,
    },
];
