import { rect, rect1, rect2, vector10, vector11, vector3, vector4, vector5, vector6, vector7, vector8, vector9 } from "./assets";

export const initialPuzzles = [
    {
        id: 1,
        sizeX: 7,
        sizeY: 4,
        correctX: [5],
        correctY: [1,3],
        src: rect,
        startPuz: {
            rotation: -19,
            left: 15,
            top: 55,
        },
        puzzWidth: 94,
        puzzHeight: 54,
        puzzRealWidth: 126,
        puzzRealHeight: 72,
        rectColor: '#A39CFF',
    },
    {
        id: 2,
        sizeX: 2,
        sizeY: 6,
        correctX: [3],
        correctY: [1],
        src: rect1,
        startPuz: {
            rotation: 97,
            left: 167,
            top: 10,
        },
        puzzWidth: 27,
        puzzHeight: 81,
        puzzRealWidth: 36,
        puzzRealHeight: 108,
        isOnlyPosition: true,
        rectColor: '#2ADBDB',
        borderRadius: (ratio) => `${ratio * 5}px 0 0 0`,
    },
    {
        id: 3,
        sizeX: 3,
        sizeY: 6,
        correctX: [12],
        correctY: [1],
        src: rect2,
        isOnlyPosition: true,
        startPuz: {
            rotation: -18,
            left: 19,
            bottom: 30,
        },
        puzzWidth: 41,
        puzzHeight: 81,
        puzzRealWidth: 54,
        puzzRealHeight: 108,
        yPosition: '100%',
        rectColor: '#FF605C',
        borderRadius: (ratio) => `0 ${ratio * 5}px 0 0`,
    },
    {
        id: 4,
        sizeX: 6,
        sizeY: 2,
        correctX: [3, 9],
        correctY: [7],
        src: vector3,
        startPuz: {
        rotation: 75,
        right: 1,
        top: 80,
        },
        puzzWidth: 81,
        puzzHeight: 27,
        puzzRealWidth: 108,
        puzzRealHeight: 36,
        rectColor: '#FF605C'
    },
    {
        id: 5,
        sizeX: 7,
        sizeY: 2,
        correctX: [5],
        correctY: [1, 5],
        src: vector4,
        startPuz: {
        rotation: -13,
        left: 90,
        bottom: 90,
        },
        puzzWidth: 94,
        puzzHeight: 27,
        puzzRealWidth: 126,
        puzzRealHeight: 36,
        rectColor: '#2ADBDB',
    },
    {
        id: 6,
        sizeX: 5,
        sizeY: 2,
        correctX: [1],
        correctY: [11],
        src: vector5,
        isOnlyPosition: true,
        startPuz: {
            rotation: -75,
            left: 10,
            top: 220,
        },
        puzzWidth: 65,
        puzzHeight: 26,
        puzzRealWidth: 90,
        xPosition: '100%',
        yPosition: '100%',
        puzzRealHeight: 36,
    },
    {
        id: 7,
        sizeX: 3,
        sizeY: 2,
        correctX: [14],
        correctY: [11],
        isOnlyPosition: true,
        src: vector6,
        startPuz: {
            rotation: 30,
            left: 105,
            top: 115,
        },
        puzzWidth: 40,
        puzzHeight: 27,
        puzzRealWidth: 54,
        puzzRealHeight: 36,
    },
    {
        id: 8,
        sizeX: 8,
        sizeY: 2,
        correctX: [6],
        correctY: [11],
        src: vector7,
        startPuz: {
            rotation: 0,
            left: 120,
            bottom: 20,
        },
        puzzWidth: 108,
        puzzHeight: 27,
        puzzRealWidth: 144,
        puzzRealHeight: 36,
        rectColor: '#2ADBDB'
    },
    {
        id: 9,
        sizeX: 4,
        sizeY: 2,
        correctX: [12],
        correctY: [9],
        src: vector8,
        startPuz: {
            rotation: 35,
            right: 58,
            bottom: 95,
        },
        puzzWidth: 54,
        puzzHeight: 27,
        puzzRealWidth: 72,
        puzzRealHeight: 36,
        xPosition: '50%',
        yPosition: '100%',
    },
    {
        id: 10,
        sizeX: 4,
        sizeY: 2,
        correctX: [8],
        correctY: [9],
        src: vector9,
        startPuz: {
        rotation: 80,
        right: 10,
        top: 240,
        },
        puzzWidth: 54,
        puzzHeight: 27,
        puzzRealWidth: 72,
        puzzRealHeight: 36,
        rectColor: '#2ADBDB'
    },
    {
        id: 11,
        sizeX: 6,
        sizeY: 2,
        correctX: [2],
        correctY: [9],
        src: vector10,
        isOnlyPosition: true,
        startPuz: {
            rotation: -30,
            right: 5,
            bottom: 50,
        },
        puzzWidth: 81,
        puzzHeight: 27,
        puzzRealWidth: 108,
        puzzRealHeight: 36,
        yPosition: '100%',
    },
    {
        id: 12,
        sizeX: 6,
        sizeY: 2,
        correctX: [3, 9],
        correctY: [7],
        src: vector11,
        startPuz: {
        rotation: -10,
        right: 85,
        top: 98,
        },
        puzzWidth: 81,
        puzzHeight: 27,
        puzzRealWidth: 108,
        puzzRealHeight: 36,
        rectColor: '#A39CFF',
    },
];


export const initialPlaced = [
    {x: 0, y: 0}, {x: 0, y: 1}, {x: 0, y: 2}, {x: 0, y: 3}, {x: 0, y: 4}, 
    {x: 0, y: 5}, {x: 0, y: 6}, {x: 0, y: 7}, {x: 0, y: 8}, {x: 0, y: 9},
    {x: 0, y: 10}, {x: 0, y: 11}, {x: 0, y: 12}, {x: 0, y: 13},
    {x: 1, y: 0}, {x: 1, y: 1}, {x: 1, y: 2}, {x: 1, y: 3}, {x: 1, y: 4}, 
    {x: 1, y: 5}, {x: 1, y: 6}, {x: 1, y: 7}, {x: 1, y: 8}, {x: 1, y: 9},
    {x: 2, y: 0}, {x: 2, y: 1}, {x: 2, y: 2}, {x: 2, y: 3}, {x: 2, y: 4}, 
    {x: 2, y: 5}, {x: 2, y: 6}, {x: 2, y: 7}, 
    {x: 17, y: 0}, {x: 17, y: 1}, {x: 17, y: 2}, {x: 17, y: 3}, {x: 17, y: 4}, 
    {x: 17, y: 5}, {x: 17, y: 6}, {x: 17, y: 7}, {x: 17, y: 8}, {x: 17, y: 9},
    {x: 17, y: 10}, {x: 17, y: 11}, {x: 17, y: 12}, {x: 17, y: 13},
    {x: 16, y: 0}, {x: 16, y: 1}, {x: 16, y: 2}, {x: 16, y: 3}, {x: 16, y: 4}, 
    {x: 16, y: 5}, {x: 16, y: 6}, {x: 16, y: 7}, {x: 16, y: 8}, {x: 16, y: 9},
    {x: 15, y: 0}, {x: 15, y: 1}, {x: 15, y: 2}, {x: 15, y: 3}, {x: 15, y: 4}, 
    {x: 15, y: 5}, {x: 15, y: 6}, {x: 15, y: 7}, 
];